### ISSUE TITLE
QS Update

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#113]

**Comment by Tyson1991** [comment]
Handy Basiert Updaten ?! und einstellen ?!

**Comment by Keykubad42** [comment]
Kommt mit qs updates

**Comment by Asrothear** [comment]
In QS Update umbenannt

**Comment by Asrothear** [comment]
Das Smartphone System scheint nicht vollständig zu sein. Entweder findet eine komplette Neuinstallation von QS statt, um die gesamte Struktur zu verbessern, oder nur einzelne Updates, um die entsprechenden Probleme zu beheben.

**Comment by Asrothear** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/312
