### ISSUE TITLE
MD- Schadenssystem

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#12]

**Comment by Tyson1991** [comment]
script schadensystem um verletzung an der person festzustellen.-

**Comment by Tyson1991** [comment]
Script für schaden muss gefunden werden das auf fl hat schon gereicht. 
Man brauch eine Funktion die abfragt wo der schaden bei der person ist und dort ein symbol oder so hinpacken.
Person a die ein kopfschuss bekommen hat soll vom medic begutachtbar sein. Der Medic soll sehen können wo der schaden her kommt.

Wenn ihr so etwas nicht findet, so etwas gibt es aber sonst einfach selbst schrieben?

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/5f0ec5c13dd7986a5c5988669676635a51d11d29
