### ISSUE TITLE
Gefängniss Ausbruch Script

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#122]

**Comment by Keykubad42** [comment]
MLO gefunden nun wird überlegt inwiefern man das macht eventuell mit Schloss an der Tür für die man ein Item brauch

**Comment by Keykubad42** [comment]
MLO dafür eingefügt nun wird dies mit einem Schloss und item etc. verknüpft

**Comment by Keykubad42** [comment]
https://github.com/Asgard-RP/Backlog/issues/348
https://github.com/Asgard-RP/Backlog/issues/347

Robberiescreator: Hacking Panels wurden eingefügt. Man muss erstmal drauf kommen das man Türen hacken muss. Und dann muss man noch den EIngang finden. Und für alles hat man nur 15 min Zeit.
