### ISSUE TITLE
Cardealer Autos anpassen

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#161]

**Comment by Keykubad42** [comment]
Rudi passt vanilla autos an

**Comment by Keykubad42** [comment]
Alle Autos in dem Datenbankeintrag "vehicles" umgestellt. Unnötige rausgelöscht, die gewünschten reingetan, alle sind zwar kaufbar, allerdings funktioniert das mit der Kategorie nicht. Die Fahrzeuge werden irgendwie keiner Kategorie hinzugefügt

**Comment by Tyson1991** [comment]
Sql Datenbank Kategorien immer Kleinschreiben.
