### ISSUE TITLE
Tätowierer speichern UI

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#165]

**Comment by Keykubad42** [comment]
tätoowierer noch nicht funktionsfähig

**Comment by Tyson1991** [comment]
Tättowierer Funktioniert hab es aussporbiert

**Comment by Keykubad42** [comment]
bro was genau hast du ausprobiert ich meine das sind zwei tättovierer scripts die jetzt übereinander liegen

**Comment by Tyson1991** [comment]
mx_tattos nochmal entfernt

**Comment by Tyson1991** [comment]
Tättowierer Funktioniert jetzt. Gerade getestet nur noch einer
