### ISSUE TITLE
Tasten Hotkeys entfernen

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#167]

**Comment by Keykubad42** [comment]
Alle mir bekannten Hotkeys:
Mausrad und b = Hand heben
x gedrückt halten = hände heben
u = umfallen
n = keine ahnung dort steht "you dont have acces to do this"
h = Hände heben
p = Map öffnen (lieber auf m)
Und irgendwie pfeift man auch noch

**Comment by mjiruobe** [comment]
Pfeifen war auf N - rausgenommen, Hand heben ist nun auf B statt Mausrad, Hände heben auf x befindet sich in qs inventory und die Funktion wird hoffentlich durch ein Update gefixt, 

Map, Hände hoch auf H sowie Voicereichweite muss ich noch finden

**Comment by mjiruobe** [comment]
H für Hände heben in krz_personalmenu auskommentiert
