### ISSUE TITLE
Adminkleidung fixxen

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#170]
baut auf #237 auf. Adminmenü muss funktionieren damit kleidung geändert werden kann

**Comment by Tyson1991** [comment]
Was genau muss Gefixt werden Bitte kommentieren ?

**Comment by Keykubad42** [comment]
Sobald Kleidungspack hinzugefügt, muss die Kleidung angepasst werden.

**Comment by Asrothear** [comment]
Kleidungspack ist drinnen, welche Kleidung soll nun gesetzt werden?

**Comment by Keykubad42** [comment]
Das Klediungspack ist allerdings etwas verbuggt das heißt im kleiodungsladen z.B. bei oberteilen ab 350-570 oder so sind die kleidungen nicht mehr vorhanden bzw öffnen sich nicht weiß nicht worand as leigt deshalb muss man da erstmal schauen

**Comment by AGNayzon** [comment]
Ist gefixed
