### ISSUE TITLE
Algorithmus das man stündlich Lohn bekommt

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#193]
Es_Extended Einstellung 
Config.EnableSocietyPayouts = true -- Bezahlen Sie von dem Gesellschaftskonto, auf dem der Spieler beschäftigt ist? Anforderung: esx_society
Config.EnableHud = false -- das Standard-HUD aktivieren? Aktuellen Job und Konten anzeigen (schwarz, Bank & Bargeld)
Config.MaxWeight = 400 -- the max inventory weight without backpack
Config.PaycheckInterval = 60 * 60000 -- Wie oft Sie Gehaltsschecks in Millisekunden erhalten
Config.EnableDebug = false

Dürfte alles eingestellt sein Prüfe noch die Jobs an sich selber Gruss Tyson

**Comment by Tyson1991** [comment]
Es_Extended Einstellung
Config.EnableSocietyPayouts = true -- Bezahlen Sie von dem Gesellschaftskonto, auf dem der Spieler beschäftigt ist? Anforderung: esx_society
Config.EnableHud = false -- das Standard-HUD aktivieren? Aktuellen Job und Konten anzeigen (schwarz, Bank & Bargeld)
Config.MaxWeight = 400 -- the max inventory weight without backpack
Config.PaycheckInterval = 60 * 60000 -- Wie oft Sie Gehaltsschecks in Millisekunden erhalten
Config.EnableDebug = false

Dürfte alles eingestellt sein Prüfe noch die Jobs an sich selber Gruss Tyson

**Comment by Tyson1991** [comment]
Hat jemand dafür eine Lösung wo das Problem liegen könnte ?

**Comment by Asrothear** [comment]
Von esx_soceity wird nicht verwendet da das Rework ein leak zu sein scheint, es lässt sich nicht starten
![image](https://user-images.githubusercontent.com/38018660/191007691-35fb97cb-c398-4f50-9396-b96669ecc5c4.png)

**Comment by Kenshiin13** [comment]
@Asrothear Einfach noch mal neu von derem Github runterladen das esx_society.
https://github.com/esx-framework/esx-legacy/tree/main/%5Besx_addons%5D/esx_society

**Comment by Keykubad42** [comment]
Bekomme Lohn habe ich gerade gesehen, weiß allerdings nicht in welchem Zeitabstand. Zudem muss man die Funktion dass die Löhne von den Fraktionskassen ausgezahlt wird am besten entfernen

**Comment by Asrothear** [comment]
Den Paycheck gibt es jede Stunde

**Comment by Tyson1991** [comment]
Alles Erledigt, Lohn auf 1h Stunde eingestellt, und das Geld vom Fraktionskonto für das Gehalt bezahlt wird Deaktiviert
