### ISSUE TITLE
Heists ersetzen neue einfügen (Robberies creator)

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#2]

**Comment by Tyson1991** [comment]
Schon gekauft ?

**Comment by Keykubad42** [comment]
Ist gekauft, der der das einfügen will schaut einfach mal in den Ordner [please Ordner] und installiert es und stellt alles ein. In der Read Me steht alles

**Comment by Kenshiin13** [comment]
Ist installiert, den Rest erledigt vermutlich @Keykubad42

**Comment by Keykubad42** [comment]
Alle Shops bei denen es vom RP Sinn gemacht hat ein RObberie riengemacht. Bei der Staatsbank und Paletobank sist es weitaus ausführlicher. Mit mehren Etappen und mehreren Schwierigkeiten. 

Hier eine Liste mit allen möglichen Raubüberfällen: (SG Ausbruch ist zu vernachlässigen, dies ist nur die Ausbruchmöglichkeit für das SG dort wurden nur die selben Tools benutzt. Es gibt somit 13 Shops die man überfallen kann von insgesamt 22 und zwei größere Räube



![Image](https://user-images.githubusercontent.com/109434078/194224451-9ef5947e-608c-4113-b1a5-b4de061bf9d6.png)
