### ISSUE TITLE
Drugscreator übersetzen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#200]

**Comment by Tyson1991** [comment]
Locales kannst du einstellen deutsche Übersetzung ist vorhanden, 
geh dazu in die Config vom Skript 
suche dort Locales in der Regel so "en" dort kannst du unter Locales auf "de" vorhanden

**Comment by Tyson1991** [comment]
Anscheinend ist die Übersetzung "Deutsch unvollständig" Dadurch entstehen Fehler bei dem Script, Übersetzung anpassen und auf Korrecktheit prüfen gegebenfalls Updaten oder nachfragen beim entwickler vom DRUGCREATOR

**Comment by mjiruobe** [comment]
Das stimmt! Die deutsche Übersetzung war unvollständig. Nun ist alles drin mit dem neuen Pull Request

**Comment by Keykubad42** [comment]
Pull request wurde bereits überprüft geschlossen
