### ISSUE TITLE
Mapping: Maze Bank Arena

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#211]
Maze Bank Arena komplett leer drinnen. Vanilla Intereur nicht da

**Comment by Tyson1991** [comment]
Ich arbeite dran, denke es benötigt ein Korrecktes Update. Prüfe das noch

**Comment by Asrothear** [comment]
![image](https://user-images.githubusercontent.com/38018660/191001743-a9907681-c662-4085-8e5c-d069fa67ebcd.png)
