### ISSUE TITLE
LS Customs Blips, unnötige Tuner rauslöschen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#213]

**Comment by Kenshiin13** [comment]
Was muss da gemacht werden? Ist das noch aktuell? @Keykubad42

**Comment by Keykubad42** [comment]
Das mache ich schon muss aber warten das mark fertig ist

**Comment by Tyson1991** [comment]
@Keykubad42 bitte mal Korreckt erklären

**Comment by AGNayzon** [comment]
PLZ 101 und 200 bleiben.
Die restlichen müssen entfernt werden
