### ISSUE TITLE
Mapping Vanilla 2025 Drughouse weg

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#217]

**Comment by Asrothear** [comment]
![image](https://user-images.githubusercontent.com/38018660/191002832-9ad546ae-b513-48f0-b26d-c5873f9d4f46.png)
![image](https://user-images.githubusercontent.com/38018660/191002881-4ed5da33-ef1a-463e-8043-10335bb231dc.png)
