### ISSUE TITLE
Custom-Shop-Menü identifizieren

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#218]

**Comment by Keykubad42** [comment]
Wenn man beim Ambulancejob F6 drückt öffnet sich ein Custom Shop Menü statt den Interaktionsmenü

Besitzt das Interface von Quasar. Wahrscheinlich ein Script von Quasar

**Comment by Asrothear** [comment]
Scheint QS zu sein, ich habe die Taste für Ambulance auf F7 gestellt
