### ISSUE TITLE
Vanilla location des Cardealers verbuggt

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#220]

**Comment by Keykubad42** [comment]
![image](https://user-images.githubusercontent.com/109434078/190937271-9c787dc2-c37e-4845-a69c-71145ce18982.png)

**Comment by Asrothear** [comment]
![image](https://user-images.githubusercontent.com/38018660/191003116-72d4abb4-c24b-4318-a2cb-c411244d8fae.png)
