### ISSUE TITLE
Unsere Standard Progressbar wie bei cannabisfarmen oder minershop auch beim drugscreator

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#221]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/191140115-905f0461-2bad-4b2e-82d2-4a2e7f160da9.png)

**Comment by Asrothear** [comment]
Standart soll die von qs werden siehe #233

**Comment by Kenshiin13** [comment]
Duplicate of https://github.com/Asgard-RP/Backlog/issues/233
