### ISSUE TITLE
f5 interkationsmenü ui ändern

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#225]

**Comment by Keykubad42** [comment]
muss noch vor alpha gemacht werden, da dort flash v steht. Mir sagen wo die ui als link ist ich ändere es direkt

**Comment by Asrothear** [comment]
Informationen dazu -> 
https://github.com/Asgard-RP/Dev-Server/commit/d1e549776f49d0387464cc40730701c29da16949#commitcomment-84498246
Es scheint kein Direktes Bild zu sein allerdings sind .ytd daten vorhanden
