### ISSUE TITLE
Add on Fahrzeugen Bilder geben für qs garage

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#228]

**Comment by Kenshiin13** [comment]
Gkay & Nayzon kümmern sich darum

**Comment by Keykubad42** [comment]
Keine AHnung wieso das nicht klappt der übernimmt die Änderungen irgnedwie dort nicht. 
Man muss sowohl die bilder im ordner img in html reinpacken als auch die farhzeuge in der vehicles.lua registieren obwohl alles gemacht wurde funktioniert es nicht wie es soll
