### ISSUE TITLE
Kleidungs Pack einzelne Objekte nicht verfügbar

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#230]
@Keykubad42 Welche dinge genau sind nicht verfügbar?

**Comment by Keykubad42** [comment]
Wurde bereits rausgehauen daher wird die Prio nun runtergestellt, im späteren Verlauf (Beta) könnte man die funktionierenden einzelne Kleidungen rausziehen

**Comment by Kenshiin13** [comment]
Nicht mehr aktuell.
