### ISSUE TITLE
Tattoostudio keine Funktion Tatoostudiofunktions Script notwendig

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#232]

**Comment by Keykubad42** [comment]
@Tyson1991 Tyson hast du vielleicht etwas?

**Comment by Tyson1991** [comment]
Ich habe etwas und packe das mal als Test rein @Keykubad42

**Comment by Tyson1991** [comment]
![Image](https://user-images.githubusercontent.com/109436524/191414233-1af73611-d9de-48de-8f95-01594a884979.png)

**Comment by Tyson1991** [comment]
ist eingefügt und Funktioniert @Keykubad42
