### ISSUE TITLE
Mapping MLO Hangar in Cayo (siehe Comment)

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#236]

**Comment by Keykubad42** [comment]
Hangar in Cayo hat eine Öffnung in der man reinfallen kann, vielleicht leigt das am Cayo selbst? @Tyson1991 
Coords: 4447.0415, -4481.4946, 4.2681, 17.5684


![Image](https://user-images.githubusercontent.com/109434078/191650413-fa4952e6-b90e-4e63-985b-4c0eab0a4cbd.png)

**Comment by Keykubad42** [comment]
Tyson kümmert sich darum eventuell ersetztz er einige dateien von cayo um das zu beheben oder arbeitet den Fehler per Codewalker aus

**Comment by Tyson1991** [comment]
![Image](https://user-images.githubusercontent.com/109436524/192339981-5c4dcf40-502f-4bb4-8334-5e938d5e41e4.png)
