### ISSUE TITLE
Adminmenü optimieren

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#237]

**Comment by Keykubad42** [comment]
Einführung mehrer Funktionen:
[Ich denke Kenshin eignet sich am besten, weil er das Script gemacht hat]

Folgende Admin-Funktionen müssen hinzugefügt/bearbeitet werden:
Hinzufügen:
/givecar [ID] [Spawnname vom Auto] [Kennzeichen]
Wenn das [Kennzeichen] Feld nicht benutzt wird kriegt die person ein zufälliges Auto
/ausreise [ID]
Wenn die Person ausgereist wird, dann wird diese für 3 Stunden gebannt mit dem Grund: _"Leider hast du unsere Whitelist nicht bestanden. Bitte komme in 3 Stunden ein erneutes mal um dich wieder an der Whitelist zu versuchen". -> irgendwie so nen text
/clearweapon [ID]
Entfernt alle waffen eines Spielers, die er im inverntar dabei hat
/Ban [ID] [Grund]
Ban verknüpfung mit TX erstellen -> ohne Grund kein Bann möglich!
/Kick [ID] [Grund]
Kick verknüpfung mit TX erstellen -> ohne Grund kein kick möglich!
/Warn [ID] [Grund]
Warn verknüfung mit TX erstellen -> ohne Grund kein warn möglich!
/Announce [Text]
Nachricht an alle User die online sind
/Givemoney [ID] [Anzahl]
Einen User geld geben 

Sobald man im Aduty ist soll man über ^ in den Noclip gehen können.
-> Sprich Keybind der erst funktioniert, wenn man im Aduty ist

Bearbeiten:
/repair
muss mal drüber geschaut werden, sobald man diesen benutzt fährt das auto nicht mehr vorwärts nur noch rückwärts
/clearinventory [ID]
Waffen sollen bleiben
/goto [ID]
ist im noclip niocht möglich 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Ich schicks dir schonmal
Asro scheint nicht mehr on zu kommen heute

Supporter:
/Warn [ID]
     -> Warnt einen User
/Kick [ID]
     -> Kickt einen User
/Ban [ID]
     -> Bannt einen User
/Revive [ID]
     -> Wiederbelebt einen User
/Einreiseamt
     -> In die Einreise
     -> Aus der Einreise
/Einreise [ID]
     -> Reist einen User ein
/Ausreise [ID]
     -> Reist einen User für 3 Stunden aus

Gamemaster:
Alles von Oben
/Aduty [ID]
     -> Admin-Anzug
/Noclip
     -> Vanish-Modus
/DV [Radius]
     -> Auto entfernen

Administration:
Alles von Oben
/Repair
     -> Repariert ein Fahrzeug
/Giveitem [ID] [Item] [Anzahl]
     -> Gibt einem User ein Item
/Giveweapon [ID] weapon__[Waffe] [Munition]
     -> Gibt einem User eine Waffe
/Announce [Text]
     -> Textnachricht an alle User
/Clearinventory [ID]
     -> Löscht alle Items eines Users
/Clearweapon [ID]
     -> Löscht alle Waffen eines Users

Management:
Alles von Oben
/Givecar [ID] [Spawnname] [Kennzeichen]
     -> Gibt einem User ein Auto in seine Garage
/Givemoney [ID] [Anzahl]
     -> Gibt einem User Geld auf sein Konto
/Setgroup [ID] [Group]
     -> Ändert den Rang eines Users_

**Comment by Kenshiin13** [comment]
Kannst der Liste bei GitHub eben folgendes hinzufügen:
Adminmenü Optimieren:
/heal [ID]
     -> gibt dem User Leben Voll, Essen Voll, Trinken Voll

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/313

**Comment by AGNayzon** [comment]
"/givecar [Spawnname] [Kennzeichen]"
fixen: Autos mit Custom Kennteichen kann man nicht in der Garage einparken.

"/Aduty"
Kleidung wird nicht verändert.

**Comment by AGNayzon** [comment]
**_User:_**
- Kann "VIELE" Befehle!

**_Supporter:_**
- Kann *JEDEN* Befehl! 

**_Gamemaster:_**
- Kann *JEDEN* Befehl!

**_Administration:_**
- Kann *JEDEN* Befehl!

**_Management:_**
- Kann *JEDEN* Befehl!

### UMGEHEND ÄNDERN!
     - Siehe im Discord unter "---- Team Informationen ----", dann "📌┃𝙄𝙣𝙛𝙤𝙨" wie die gesetzt werden müssen

**Comment by AGNayzon** [comment]
### Muss noch hinzugefügt werden:
"/Warn [ID]"
"/Kick [ID]"
"/Bann [ID]"
"/Ausreise [ID]"
"/Noclip"
"/Announce [Text]"
"/Clearweapon [ID]"
"/heal [ID]"
x = in Noclip gehen
-> nur wenn man im Aduty ist

### Bug:
"/Aduty" 
- Kleidung ist verbuggt
- Name Tags gehen nur bei "Leitunsebene" -> alle sollen das können

"/clearinventory"
- Notify kommt sowohl bei Admin als auch bei User, funktioniert aber nicht

**Comment by AGNayzon** [comment]
Teleportieren auf "ALT + E"
Noclip auf "x" NUR wenn man im Aduty ist

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/367
