### ISSUE TITLE
Beim f5 interaktionsmenü funktionen entfernen (siehe comments)

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#245]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/192075137-de30af09-9382-45ae-9f80-acaebe34d6a5.png)


Rot entfernen

**Comment by Keykubad42** [comment]
Eventuell Design wie bei esx menu default?

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/363
