### ISSUE TITLE
Blitzer anpassen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#252]

**Comment by Keykubad42** [comment]
Habe es installiert, allerdings müsste am client angepasst werden, dass man mehrere Coords geben kann und für die die Tempozone auch noch einzeln definieren kann

**Comment by Kenshiin13** [comment]
Was hältst du von den Blitzen von dem Typen https://store.londonstudios.net/category/resources

Die kann man auch wirklich sehen und auch mehrere aufstellen.

@Keykubad42

**Comment by Keykubad42** [comment]
NE bitte einfach Code umschrieben das man mehrere haben kann und notify bitte okoknotify nutzen

**Comment by Asrothear** [comment]
Wo ist das Script denn zu finden?

**Comment by 69Gkay** [comment]
done
