### ISSUE TITLE
Dmvschool Motorrad und Lkwprüfung muss man nur kaufen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#257]

**Comment by Keykubad42** [comment]
Gerade muss man die Theorieprüfung machen, und dann kann man die prakitsche prüfung mahcen für lkw motorrad oder auto. Die slebe Route muss man abfahren. Es würde mehr SInn machen wenn man einmal diese Prüfung macht mit Auto und Motorrad und Lkw dann einfach nur nachkaufen muss

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/368
