### ISSUE TITLE
Jobcenter zeigt nicht die richtigen Jobs an

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#259]

**Comment by Keykubad42** [comment]
Obwohl JObs gewhitleisted sind in job.sql im php, zeigt der nur dreimal das Casino an im Jobcenter. Da frage ich mich auch wieso er drei verschiedene Ränge vom Casino anzeigt. Wo registriert er das drei verschiedene Ränge dort angezeigt werden soll

**Comment by Asrothear** [comment]
![image](https://user-images.githubusercontent.com/38018660/193131116-d870f814-ea23-47ef-9dfa-3bba7fee0b50.png)
Ich schreibe in die Ressource eine Readme mit Informationen wie Jobs im JobCenter erfasst werden und in der DB einzustellen sind

**Comment by Asrothear** [comment]
resources\[FlashPack]\[Jobs]\[Jobcenter]\joblisting\README.md
Das JobCenter greift aus den Tabellen `jobs` und `jobs_grades` die Informationen der JObs inkl der Verfügbaren Ränge ab.

Mit `jobs.jobcenter` wird angegeben ob der Job im Jobcenter angezeigt werden soll. 0 = Nich gelistet, 1 = gelistet.   
Mit `jobs.fulltime` wird angegeben ob der Job im Jobcenter als "Vollzeit-Job" angezeigt werden soll.  0 = Teilzeit, 1 = Vollzeit

Es werden bei jedem Job nur der Rang mit der Level 0 angezeigt.
