### ISSUE TITLE
Blips Farbe und Icon.

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#270]
**Hinzufügen:**
- Unicorn Garage

**Ändern:**
- Krankenhaus: Blip [153], Farbe [1] x
- Kleidungsladen: Farbe [60] x
- Tankstellen: Farbe [41] x
- Waffenladen: Farbe [1] x
- Tattoo-Shop: Farbe [1] x
- Arbeitsamt: Blip [787], Farbe [69} x

**Entfernen:**
- Lester x
- Mechanic-Shop [siehe Anhang] x
![image](https://user-images.githubusercontent.com/114504764/192572439-de70102a-c317-41df-ba4d-08a8b8c8d9d0.png)
![image](https://user-images.githubusercontent.com/114504764/192572514-c22a53b9-ac4d-49e6-a8a4-44f1c9131738.png)
- Prison x

**Comment by AGNayzon** [comment]
Prison: hd_advanced_jail gelöscht

**Comment by AGNayzon** [comment]
Mechaniker: renzu_customs gelöscht

**Comment by AGNayzon** [comment]
Größen auch angepasst

**Comment by Keykubad42** [comment]
Alles erledigt!
