### ISSUE TITLE
Medic F7 menü entfernen

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#272]
Über "F7" öffnet sich das Menü fürs Reviven etc... -> auf "F6" umstellen
   -> Es soll sich sofort das EMS-Menü öffnen [ohne die Vor-Kategorie

Kleine Wunden heilen funkuniert nicht

**Comment by Tyson1991** [comment]
F6 menü deaktivert unter /home/asgard-dev/server-data/resources/[qs-scripts]/qs-shops/config/config_playershop.lua
Ambulance rausgenommenm

**Comment by Tyson1991** [comment]
unction OpenMobileAmbulanceActionsMenu()
	ESX.UI.Menu.CloseAll()

	ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'mobile_ambulance_actions', {
		title    = _U('ambulance'),
		align    = 'top-left',
		elements = {
			{label = _U('ems_menu'), value = 'citizen_interaction'}
	}}, function(data, menu)
		if data.current.value == 'citizen_interaction' then
			ESX.UI.Menu.Open('default', GetCurrentResourceName(), 'citizen_interaction', {
				title    = _U('ems_menu_title'),
				align    = 'top-left',
				elements = {
					{label = _U('ems_menu_revive'), value = 'revive'},
					{label = _U('ems_menu_small'), value = 'small'},
					{label = _U('ems_menu_big'), value = 'big'},
					{label = _U('ems_menu_putincar'), value = 'put_in_vehicle'}
			}}, function(data, menu)
				if isBusy then return end

				local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()

				if closestPlayer == -1 or closestDistance > 1.0 then
					ESX.ShowNotification(_U('no_players'))
				else
					if data.current.value == 'revive' then
						revivePlayer(closestPlayer)
					elseif data.current.value == 'small' then
						ESX.TriggerServerCallback('esx_ambulancejob:getItemAmount', function(quantity)
							if quantity > 0 then
								local closestPlayerPed = GetPlayerPed(closestPlayer)
								local health = GetEntityHealth(closestPlayerPed)

								if health > 0 then
									local playerPed = PlayerPedId()

									isBusy = true
									ESX.ShowNotification(_U('heal_inprogress'))
									TaskStartScenarioInPlace(playerPed, 'CODE_HUMAN_MEDIC_TEND_TO_DEAD', 0, true)
									Citizen.Wait(10000)
									ClearPedTasks(playerPed)

									TriggerServerEvent('esx_ambulancejob:removeItem', 'bandage')
									TriggerServerEvent('esx_ambulancejob:heal', GetPlayerServerId(closestPlayer), 'small')
									ESX.ShowNotification(_U('heal_complete', GetPlayerName(closestPlayer)))
									isBusy = false
								else
									ESX.ShowNotification(_U('player_not_conscious'))
								end
							else
								ESX.ShowNotification(_U('not_enough_bandage'))
							end
						end, 'bandage')
'

/home/asgard-dev/server-data/resources/[FlashPack]/[esx]/[jobs]/esx_ambulancejob/client/job.lua

@Asrothear könntest du bei Ambulance Job den Titel weg machen damit Nayzon nur noch die 4 hauptteile hat statt
F7 dann kommt die Oberfläche Krankenwagen und EMS Menü und dann erst das Richtige Menü 
Nayzon möchte aber das wenn du F7 direkt das Menü offen hast .

**Comment by Keykubad42** [comment]
Einfach den F7 menü beim ambulance job also ems menü entfernen! Wir benutzen das menü vom jobcreator!!
