### ISSUE TITLE
PD extras my billing etc.

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#273]
Entfernen:
- Jail-Option Menü: auf "N"
- Beim Rechnungssystem [aktuell "F7"]
   > "Objekte Spawnen" und "Rechnungen in Teilauszahlung"
       > direkt "Rechnung stellen" öffnen

Ändern:
-Rechnungen in PDExtras einarbeiten
- Rechnungen Design anpassen an Asgard Design (sowas kann Theo oder Gkay machen)
- /pdextras von "F11" auf "F7"

Übersetzen:
- /pdextras

**Comment by Tyson1991** [comment]
mybilling Hotkey entfernen 
hd_advance jail

**Comment by Tyson1991** [comment]
hd_advance jail durch @Keykubad42  entfernt und "N" somit auch entfernt

**Comment by Keykubad42** [comment]
pd extras "Rechnung" mit dem event "rechnung ausstellen" von my billing verknüpfen. Das heißt wenn man pdextras öffnet. soll sich über pd extras sobald man auf rechnung drückt direkt dieses rechnungsmenü öffnen, kein mybilling etc.

Wäre auch nice wenn du es schaffst die Funktion in pdextras zu paken um eine ressoruce zu sparen, ist aber kein muss

**Comment by Kenshiin13** [comment]
Ist erledigt, aber man kann Rechnungen nicht sehen bzw. ausstellen.

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/383

**Comment by Kenshiin13** [comment]
Design wird noch von Gkay gemacht
