### ISSUE TITLE
Lasertag Neuinstallation

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#278]

**Comment by Keykubad42** [comment]
Im Ordner [please_install] im Root ist die ressoruce aufzufinden. Ihr könnt dort dann alles installieren und das alte lazer tag rauslöschen 

Script: BUNDLE_PlasmaGame_&_PlasmaCTF_DLC_V3.2

MLO: patoche_plasmagame.pack

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/369
