### ISSUE TITLE
exs dealership übersetzen Buy Testdrive Primary Colour etc.

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#281]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/192675600-1f23d784-3b9b-4354-abe3-48c248baa399.png)

**Comment by Kenshiin13** [comment]
Gkay kümmert sich drum

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/384
