### ISSUE TITLE
[BUG] Nagelbänder funktonieren nicht

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#284]
Nagelbänder kann man über "F11" Spawnen aber die reifen bleiben heile

**Comment by Kenshiin13** [comment]
Ich werde mich später dran machen, ich weiß woran das liegt. Was hältst du davon, wenn ein Nagelband nur eine bestimme Chance hat die Reifen zu treffen? Z.b. 70-80%.

**Comment by AGNayzon** [comment]
75% top.
Vallah gefällt mir.

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/354
