### ISSUE TITLE
qs dlcs raufpacken

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#286]
Schutzwesten können gekauft aber nicht verwendet werden.

**Comment by Keykubad42** [comment]
QS dlc amor muss heruntergeladen werden aber ich warte auf den qs inventory update

**Comment by Tyson1991** [comment]
Wann Passiert das Update datum ungefähr ?

**Comment by Asrothear** [comment]
![image](https://user-images.githubusercontent.com/38018660/194383027-349a2cfe-0da8-4dad-9cfe-9fc6a7728c6e.png)
