### ISSUE TITLE
Mapping: Gabzv. bennys ist verbuggt da noch das alte Bestandsgebäude angezeigt wird liegt aber nicht am MLO

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#289]
plz 200

![Image](https://user-images.githubusercontent.com/109434078/192902732-dfce7a67-4a54-40d5-b4de-76c4d0cc9f71.png)

**Comment by Keykubad42** [comment]
Weiß nicht was gemacht wurde aber jetzt geht es

**Comment by Kenshiin13** [comment]
Muss hier noch was gemacht werden @Keykubad42?

**Comment by Kenshiin13** [comment]
Ansonsten bitte schließen.

**Comment by Kenshiin13** [comment]
Scheint gefixed zu sein.
