### ISSUE TITLE
Helikamera script raufladen und testen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#290]

**Comment by Keykubad42** [comment]
https://github.com/Zerofour04/FiveM-Helicam

Bitte schauen ob es ein Leak ist

**Comment by Kenshiin13** [comment]
Hinzugefügt und getestet mit @mjiruobe. Sieht gut aus, funktioniert so wie es soll.

https://github.com/Asgard-RP/Dev-Server/pull/370
