### ISSUE TITLE
Abschlepperscript

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#291]

**Comment by Keykubad42** [comment]
Der Job Abschleppdienst soll den Towtruck2 ausparken können und Autos abschleppen können und an der Fläche (siehe Bild) abstellen können, wenn sie sich dann der Fläche nähern soll ein Marker erscheinen, mit der notify das Auto verschrotten oder sowas. Dann bekommt er dafür 500 Dollar oder so und das Auto wird dv´t 



![Image](https://user-images.githubusercontent.com/109434078/192914537-ce417818-1de8-4dd6-9deb-7042cdb39979.png)

**Comment by Keykubad42** [comment]
Abschlepperjob erstellt
Garage erstellt

**Comment by Kenshiin13** [comment]
Gewünschtes Feature in https://github.com/Asgard-RP/Dev-Server/pull/372 hinzugefügt.
