### ISSUE TITLE
Schadensanimation entfernen

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#295]
Schadensscript muss entfernt werden.

**Comment by Keykubad42** [comment]
Gemeint ist die Animation die man bekommt sobald man weniger als Hälfte des Lebens hat. Die soll raus

**Comment by Kenshiin13** [comment]
Ich weiß nicht was ihr unter Animation versteht, deswegen habe ich einfach mal geraten was alles dazu gehört. Das Humpeln und der blurr ist z.B. noch drin. Issue bitte neu eröffnen wenn das so nicht passt.

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/409
