### ISSUE TITLE
Ladenraub ersetzen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#3]

**Comment by Keykubad42** [comment]
wichtig da Raub wichtige Beschäftigung der Badfraks ist

**Comment by Asrothear** [comment]
Womit soll das ersetzt werden, warum soll es ersetzt werden?

**Comment by Keykubad42** [comment]
Zurzeit gibt es nur einen NPC raub man bekommt 200 dollar oder so. In der fivem szene gibt es immer diesen standardraubscript Tyson müsste das zu 99,99% haben da es das auf seinem alten server hundert prozent gab es ist auch kostenlos mir ist nur der name entfallen @Tyson1991

**Comment by Tyson1991** [comment]
Keykubad was ist mit dem raubcreator ? @Keykubad42 
dann kann man das ja damit ersetzen. 
Ich hab es gesucht und schaue noch wo das ist.

**Comment by Asrothear** [comment]
@Tyson1991 hattest das hier fertig? Dann bitte wchlo

**Comment by Tyson1991** [comment]
@Asrothear @Keykubad42 ich arbeite noch dran. es ist esx_holdup standard raub Script

**Comment by Tyson1991** [comment]
unter esx_holdup kann man mehr überfälle reinbringen mit Koordinaten e.t.c

**Comment by Tyson1991** [comment]
Funktioniert müssen aussreichend Polizisten da sein
