### ISSUE TITLE
Bank, blip, staatsbank schnittstelle

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#304]

**Comment by Kenshiin13** [comment]
Bitte erklären wovon du redest

**Comment by Keykubad42** [comment]
alles geändert aber dies konnten wir nicht färben. Haben es nicht gefunden


![Image](https://user-images.githubusercontent.com/109434078/193720811-3cc8c103-946b-46e4-8511-c0a9b3d87f39.png)


Ebenfalls war es uns nicht möglich die Schriftfarbe der Kreditkarte zu ändern die würden wir gerne in schwarz haben, die Schrift an sich wird festgelegt in scirpt.js z.B. bei 684
