### ISSUE TITLE
Robberies creator/ doorscreator lockpick alarm verbessern

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#309]

**Comment by Keykubad42** [comment]
Einstellen das bei einer verwendung eines ditriches (lockpick) (nur bei türen wo das eingestellt wurde über doorscreator) nicht nur police sondern auch swat und fib eine notify und einen blip auf die karte kriegen

Die notify soll alle 10 sekunden 30 sekunden lang auftauchen also 3 mal. Und der Blip auf der KArte soll 5 Minuten halten statt 30 sek

**Comment by Keykubad42** [comment]
lockpick ist beim doorcreator

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/194208394-c24e2af3-a08a-47ba-8455-567b94fa9e14.png)

Die Meldung übersetzen habe es leider nicht gefunden

**Comment by Keykubad42** [comment]
eventuell den lockpick alarm vom doorscreator mit der app "police" verbinden

Der alarm von dem robberiescreator ist bereits mit der app verknüpft also scheint das ja möglich zu sein. Trz wäre nautrülich eine MArkierung auf der Karte hilfreich

**Comment by Kenshiin13** [comment]
hatte dazu glaub ich schon einen commit gesehen. ist das erledigt?

**Comment by Keykubad42** [comment]
https://jaksam1074.gitbook.io/jaksams-scripts-documentation/doors-creator/client/replace-default-police-alert

Da steht wie man es ändern kann
