### ISSUE TITLE
k13 tow fix

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#313]

**Comment by Keykubad42** [comment]
https://medal.tv/games/gta-v/clips/DhmpkF6vYtZbG/d1337GNITAxG?invite=cr-MSxGcVYsNjI1MDQ2MDIs

k13 tow sobald ein anderer ein auto in das feld fährt und ich das verusche abzuschleppen wird das auto nicht dvt und ich kann das unendlich mal machen

Zudem kann jeder job das auto abschleppen.  Nur Abschleppdienst soll das tun können

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/381

PS: Danke für den Earrape.
