### ISSUE TITLE
Lasertag aus 2 locations eine machen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#315]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/193659535-e0101581-0938-4016-b31f-24f73cfc2547.png)

Grün ist weg rot bleibt. Blip name geändert

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/386

rote location wird benutzt, mlo dateien  + cfg eintrag von der anderen gelöscht
