### ISSUE TITLE
Plasmagames mlo wird nicht geladen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#318]

**Comment by Keykubad42** [comment]
das mlo bei 337 wird geladen das oben aber nicht muss anders rum sein

**Comment by Kenshiin13** [comment]
Kann mir nicht erklären wieso. Bitte das MLO neu installieren @Keykubad42

**Comment by Keykubad42** [comment]
wurde gemacht @Kenshiin13
