### ISSUE TITLE
LSC Panzerung weg und Preise anpassen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#319]

**Comment by AGNayzon** [comment]
- Panzerung aus kommentieren.

Preis-Anpassung:
- Bremsen:  
2000    --     3000
3500     --    6000
5000     --    9000
- Getriebe:
  2500    --   5000
  5000    -- 10000
10000    -- 15000
- Turbolader:
10000    --  25000
- Motor:
5000     --  10000
7500     --  15000
15000   --  20000

Legende:
Links: Alter Preis
Rechts: Neuer Preis
