### ISSUE TITLE
[BUG] Unnötiger Marker, entfernen

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#329]
![image](https://user-images.githubusercontent.com/114504764/193724918-9a417c97-39dd-40e9-9fc0-f27d1cbbe3cf.png)
Ein Marker von dem MD [Krankenwagen] Skript von Tyson...

**Comment by Keykubad42** [comment]
esx ambulancejob

**Comment by Keykubad42** [comment]
k

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/431
