### ISSUE TITLE
F3 sowie F5 (M) Menü verschieben.

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#341]
Aktuell ist das Menü oben Links. Bitte wie die anderen Menüs nach unten rechts platzieren.
Waffenschule genau so
OKOK Notify rechts mittig statt oben  Gemeint ist idie notifcation in der esx weaponschool, wenn man z.B. schon eine waffenschein besitzt

**Comment by Keykubad42** [comment]
f3 und f5 sind die einzigen UI´s die nicht auf exs menu default zugreifen

**Comment by Keykubad42** [comment]
Wichtig da Vorbereitung für HUD. Hud ist oben daher müssen diese Sachen nach unten rechts


Waffenschule: hierbei handelt es sich um exs menu default


![Image](https://user-images.githubusercontent.com/109434078/194209164-28a89551-a0a9-4d6e-a37d-b69f093665a2.png)


Die HUD würde das komplett verdecken

**Comment by Keykubad42** [comment]
okok notify: 


![Image](https://user-images.githubusercontent.com/109434078/194209526-91edc1d4-b88c-4126-a100-841942d8d859.png)

quasi so nur rechts 

Gemeint ist idie notifcation in der esx weaponschool, wenn man z.B. schon eine waffenschein besitzt
