### ISSUE TITLE
k13 VehicleShop autos sollen nicht dv´t werden können

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#342]
Autos sollen nicht dv bar sein. [Asgard-Coin] Autos

**Comment by Kenshiin13** [comment]
Benutzt halt einfach nicht /dv im Autohaus xD. Aber ja, ich kann das einbauen.

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/408
