### ISSUE TITLE
[BUG] Durch Update: Nachladen

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#350]
Wenn man mit einer Waffe nachlädt, kommt die Notifikation [s. Anhang]. Auch wenn man das Item "Clip" besitzt.
![image](https://user-images.githubusercontent.com/114504764/194451285-34e18aaf-8409-46c6-8ce6-77d634d3c018.png)

**Comment by Keykubad42** [comment]
oder wenn man r drückt

**Comment by Kenshiin13** [comment]
fixed https://github.com/Asgard-RP/Dev-Server/pull/429
