### ISSUE TITLE
[BUG] Durch Update: Charselector

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#351]
Charcreator - ESX.Identits -> ESX.Skin mit vexcreator tauschen

**Comment by AGNayzon** [comment]
HUD ist zu sehen, wenn man im Charselector ist.

**Comment by AGNayzon** [comment]
Wenn man im Charcreator Menü "ESC" drück kann man nicht mehr machen und muss reloggen.

**Comment by Kenshiin13** [comment]
fixed
