### ISSUE TITLE
[BUG] Durch Update: UI´s

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#355]
- Müssen Teilweise verschoben werden. Sind teilweise nicht mehr zu sehen.

**Comment by AGNayzon** [comment]
z.B: Jobcreator ui  passt zwar unten rechts aber kann bisschen höher minimal

**Comment by Keykubad42** [comment]
was meinst du bilder bitte!

**Comment by AGNayzon** [comment]
Das war dein Kommentar in "dev-leitung"

**Comment by Keykubad42** [comment]
Dann wird dieser Punkt nun geschlossen die uis die angegeben wurden wurden alle bearbeitet!
