### ISSUE TITLE
Vexcreator: Sobald man irgendetwas am Aussehen ändert  bekommt man Schminke

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#372]

**Comment by Keykubad42** [comment]
Aussehen ändern im Vexcreator führt dazu dass man  Schminke ins Gesicht bekommt, das kriegt man auch nicht weg. Weil Männer eig keine Schminke drauf machen können

**Comment by Kenshiin13** [comment]
fixed

**Comment by Kenshiin13** [comment]
fixed
