### ISSUE TITLE
Auto abschließen Script

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#377]

**Comment by Keykubad42** [comment]
@Tyson1991  Hast du da was zu?

**Comment by Asrothear** [comment]
Warum nicht das Qs System?

**Comment by Tyson1991** [comment]
Dann QS @Keykubad42 @Asrothear

**Comment by Keykubad42** [comment]
qs ist schwirieg weil qs keys nicht mehr richtig funktioniert, @Tyson1991 such bitte was raus
