### ISSUE TITLE
Ressourcen nicht beim Serverstart anzeigen UI

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#380]

**Comment by Keykubad42** [comment]
Im Loadingscreen alle Ressorucen ausblenden

**Comment by Keykubad42** [comment]
soweit fertig @mjiruobe ?

**Comment by mjiruobe** [comment]
nach mehreren tests öffnet sich jetzt keine Resource mehr. Selber getestet, Keykubad, Tarek etc.
