### ISSUE TITLE
Geld bei Einreisen

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#384]
Aktuell bekommt man $2500 auf die Bank und $500 auf die Hand. 
Allerdings benötigt man die $500 auch im Inventar sonst sind diese nicht nutzbar.

Entweder man bekommt also das Item "money" oder man macht dann direkt $3000 auf das Konto.
-> des einreisenden

**Comment by Keykubad42** [comment]
Also das item money

**Comment by Tyson1991** [comment]
CFG einfügen ?
