### ISSUE TITLE
k13 aduty aduty fix

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#387]

**Comment by Keykubad42** [comment]
Kleidung von admin verschwindet sobald man aus aduty rausgeht. Das heißt wenn man administrator ist und in aduty reingeht und wieder rausgeht hat man z.B. keine Hose mehr etc.

Administration hat keine name tags

**Comment by Kenshiin13** [comment]
Konnte nich reproduziert werden.
