### ISSUE TITLE
ESX_Identity übersetzen + UI ändern.

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#390]
![image](https://user-images.githubusercontent.com/114504764/195121670-fd9e72d9-1334-4155-b98d-72015b1118e4.png)

**Comment by AGNayzon** [comment]
![Image](https://user-images.githubusercontent.com/114504764/195121906-88a5a9d3-f9f7-4ab8-af7c-f844c9939db5.png)



![Image](https://user-images.githubusercontent.com/114504764/195121859-433c1e4b-84a8-4b9c-88bd-42be9f9b8fc4.png)

Fertig

**Comment by AGNayzon** [comment]
Bei Github bitte hochladen @Asrothear @Keykubad42 @Kenshiin13

**Comment by Keykubad42** [comment]
hab
