### ISSUE TITLE
basicneeds funktioniert nicht ganz

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#399]

**Comment by Keykubad42** [comment]
um essen und trinken zu können mit animation muss man die ressoruce immer neu laden bringt aber ändert trz- nichts am hunger oder durst.

**Comment by Asrothear** [comment]
Möglicher weise durch Start-Reinfolge verusacht. QS Wird nun vor esx addons in der Server cfg gelistet

**Comment by Asrothear** [comment]
Laut Tests (war nicht persönlich dabei) läuft es nun
