### ISSUE TITLE
ingamevoice: die reichweite einstellen auf y statt f11 stellen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#411]

**Comment by Asrothear** [comment]
![image](https://user-images.githubusercontent.com/38018660/195886727-9e24357b-cad9-4841-9d78-3370f5055f38.png)
Wir können nur den Default setzen, wenn in der Steuerung das schon existiert oder umgestellt wurde, können wir da nichts ändern. Das muss der User dann selber machen
