### ISSUE TITLE
Fraktionsfarhzeuge abschließen können

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#424]

**Comment by Keykubad42** [comment]
/home/asgard-main/server-data/resources/[keykubad]/EUK-CarLock

Dort ist die Ressoruce. Normale Autos sprich Autos aus der privaten Garage kann man abschließen. Fraktionsfahrzeuge nicht

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/503
