### ISSUE TITLE
einsteigen geht nicht als Beifahrer

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#431]

**Comment by Keykubad42** [comment]
Discord bugreport: https://medal.tv/games/gta-v/clips/EN81h1F9L8_Sa/d1337wn3xkeP?invite=cr-MSx1eHQsNTI0NjAzMTks

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/492
