### ISSUE TITLE
Fahrzeuge bei k13 shop (vehicle, boat, plane) unzerstörbar machen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#445]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/196072335-8ff5b3da-65d1-4f47-b14b-868d2fbd3540.png)

Sowas darf nicht..

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/512
