### ISSUE TITLE
Kleidungsladen braucht die kategorie tattoo (Overlays)

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#446]

**Comment by Keykubad42** [comment]
Infos werden von Nayzon noch folgen

**Comment by Keykubad42** [comment]
@AGNayzon  @AGNayzon @AGNayzon

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/becd442fa8294ac18c6d00b3b011d7948d794840
