### ISSUE TITLE
k13 shops autos kann man mit f8 quit behalten

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#447]

**Comment by Keykubad42** [comment]
Soblad man im k13 vehicle shop, testfahrt macht unddann f8 quit macht. Kann man nach reconnect wieder damit fahren alleridngs so lange wie man will. 

Das selbe Problem ist wahrscheinlich auch bei k13boatsshop und k13planeshop

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/512/commits/c1f8a61fc4edde8dc802d0306fdc5ecd9de5a929
