### ISSUE TITLE
okokcontract nach Benutzung hat man immer noch diesen Aktenzettel in der Hand

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#453]
![Image](https://user-images.githubusercontent.com/109434078/196081806-8e800db8-8dc6-4e7d-a120-e9f2df6e370d.png)

**Comment by Keykubad42** [comment]
Ist kein Emote man kann es nicht entfernen

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/518
