### ISSUE TITLE
md tote f9, die Leiche fleigt richtig hoch nur bei dem client

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#465]

**Comment by AGNayzon** [comment]
https://medal.tv/games/gta-v/clips/F7ovvt6EeXnAO/d1337F05kADM?invite=cr-MSx3TnYsNTkxNTM2MjYs

**Comment by Keykubad42** [comment]
@mjiruobe  Das funktioniert nicht ganz. Clientseitig sieht es so aus als würde man weit weg fliegen, für die anderen aber nicht. alle anderen sehen dich an der selben Stelle können dich aber nicht reviven z.B. der Mdler. Die müssen dich carryn (tragen) und absetzen und dann können sie dich reviven. Muss auf jeden fall gefixxt werden. Oben ist ein Clip dazu
