### ISSUE TITLE
PD HELI wenn man aussteigt hat man manchmal Sniper

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#469]

**Comment by Keykubad42** [comment]
Bitte fixxen
@Kenshiin13 du sagtest ja es liegt and er handling meta

/home/asgard-main/server-data/resources/[Cars]/[Staatsfrakautos]/PD-Helicopter

Bitte schau dir das an, was amn machen muss. Du hast das ja schonmal gemacht. Rudi weiß nicht wie

**Comment by Kenshiin13** [comment]
Das war doch bereits mit Rudi behoben worden.
