### ISSUE TITLE
GTA Vanilla Munitionsanzeige entfernen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#472]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/196338954-da029bb7-b78b-448f-9cc4-f6321cc6f9a8.png)

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/56cdececace8a47b28816e80d01aa0ed869ab712
