### ISSUE TITLE
QS handy techniker entfernen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#473]

**Comment by Kenshiin13** [comment]
![Image](https://user-images.githubusercontent.com/63159154/196706298-378c743c-47b2-41f7-b2b0-3fbd8e8778c5.png)


![Image](https://user-images.githubusercontent.com/63159154/196706720-09b5cd99-d02b-4226-98a9-d303a3da6d8e.png)



Mehr als das habe ich in der Config nicht gefunden. In der Dokumentation sehe ich auch nicht wirklich etwas. Bitte im Support bei qs fragen.

**Comment by Keykubad42** [comment]
Müssen qs erstmal nochmal updaten vielleicht ist das ja dann weg :)

**Comment by Keykubad42** [comment]
Smartphone update soll das laut qs beheben ja moin sehr schön
