### ISSUE TITLE
personalausweis etwas verbuggt

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#482]

**Comment by Keykubad42** [comment]
https://user-images.githubusercontent.com/109434078/196576826-ceff97ff-dde7-4951-ad8b-b443a88c455d.mp4

**Comment by Kenshiin13** [comment]
Was genau ist da jetzt verbuggt?

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/pull/519
