### ISSUE TITLE
Tankstellen Preise verändern

### ISSUE THREAD

**Issue by Asrothear** [Asgard-RP/Backlog#49]

**Comment by Keykubad42** [comment]
Soll Zufallgenerator sein zwischen 1 und 3 dollar. Nach jedem Restart soll jede Tankstelle andere Preise haben. Ist das nicht so einfach möglich, dann einfachf erstmal Festpreis von 2 dollar reinsetzen

**Comment by Keykubad42** [comment]
Preise sind gerade ok kann so bleiben erstmal
