### ISSUE TITLE
k13 vehicleshop bug, auto bei testfahrt verschwindet nicht

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#492]

**Comment by Keykubad42** [comment]
https://medal.tv/games/gta-v/clips/FgdZMYGwoFh-b/d1337ObK3SaN?invite=cr-MSx5eG8sNjI1MDQ2MDIs

**Comment by Kenshiin13** [comment]
Ich habe leider überhaupt keinen Ansatzpunkt was den Bug verursachen könnte. Muss ich mir durch den Kopf gehen lassen und noch mal drüber schlafen.

**Comment by Keykubad42** [comment]
Das eine hast du ja bereits gefixxt, aber das mit dimension wolltest du ja noch fixxen bitte auch das hier beachten:

https://medal.tv/games/gta-v/clips/FqUn5zpshPyj_/d1337m2PXyUQ?invite=cr-MSxreHosNjI1MDQ2MDIs

**Comment by Kenshiin13** [comment]
Was ist das?

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/41c96992aae46a1605406daca74abc3fece85841
