### ISSUE TITLE
md porsche horn wieder aktivieren

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#504]

**Comment by Keykubad42** [comment]
Ausgangssituation:
Der Porsche des MD, der im Md Carpack ist unter cars staatsfrakautos, dort funktioniert ide sirene nicht. Also man hört nichts.

Reproduktion der Ausgangssituation:
Man sitzt im Auto drückt q oder so

Vermutung:
No idea

Gewünschte Situation:
Horn soll erklingen

**Comment by Kenshiin13** [comment]
fixed by Rudi
