### ISSUE TITLE
k13 aduty givecar command

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#506]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/197315440-1f786f0f-7b84-4a2e-827a-7780425fac06.png)

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/f9715ec7b68b8056d706b672e4be420c08066514


![Image](https://user-images.githubusercontent.com/63159154/197396225-68f18bf0-a737-4ffc-96fb-d75bf9fbb51c.png)
