### ISSUE TITLE
lebensanzeige zeigt an das man leben verliert..

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#507]

**Comment by Keykubad42** [comment]
https://medal.tv/games/gta-v/clips/FyZYNaY3Jtc4h/d1337KSK7tV1?invite=cr-MSxoZG8sNjI1MDQ2MDIs

**Comment by Keykubad42** [comment]
DIe anzeige unter der map unten zeigt an das man leben verleirt i dont know why

Eigentlich kann die anzeige unter der map auch komplett weg

**Comment by Keykubad42** [comment]
Ist erst seit heute da

Habe heute was an qs core geändert
Fahrzeug bilder eingefügt in qs garages
und du eben den vehicleshop gefixxt das wars

asro hatte die hud angepasst aber die Änderung ist glaube noch nicht mal auf dem main server

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/3a3e9e6e5f85ba6f4921858355bc2db067cc0542


![Image](https://user-images.githubusercontent.com/63159154/197399649-d8285f9d-21cd-4fba-a17a-026314733678.png)
