### ISSUE TITLE
Extra funktion beim Aduty

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#508]
![image](https://user-images.githubusercontent.com/114504764/197336414-15f9e379-ed92-4cae-bff9-ffd4f200b756.png)
Eine Funktion einbringen, die es ab **MANAGEMENT** möglich macht, die User wie bei dem bild zu sehen ist, zu sehen

**Comment by Kenshiin13** [comment]
Ist es auch möglich einfach eine Box um die User zu zeichnen?

**Comment by Keykubad42** [comment]
wallhack oder pc
