### ISSUE TITLE
k13 aduty clear inventory bug?

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#517]

**Comment by Keykubad42** [comment]
clear inventory soll zu bugs führen (siehe Bild) Ticket wurde auch extra noch nicht geschlossen. Ich selber konnte es aber nicht reproduzieren



![Image](https://user-images.githubusercontent.com/109434078/197427604-e8a5709b-407d-4818-8747-43e55b5e9d46.png)

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/7a8b85b3821c2e3b58b36e6c057ae36ece251cd6
