### ISSUE TITLE
Beim Tod kann man per f8 quit einfach wieder reconnecten und wacht LEBEND an dem selben Spot auf

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#518]

**Comment by Keykubad42** [comment]
Ausgangssituation:
Wenn man stirbt, kann man per f8 quiten und dann wenn man wieder connectet, lebt man wieder und spawnt am selben Spot wo man gestorben ist.

Reproduktion der Ausgangssituation:
1. sterben
2. f8 quit
3. reconnect & spawn

Vermutung:
No Idea

Gewünschte Situation:
Möglichkeit 1: 
Das man auf jeden Fall bei soetwas am MD aufwacht, dort wo man auch spawnt wenn man ganz normal ausblutet. 

Möglichkeit2: (Besser aber schwerer)
Besser wäre noch wenn vor dem quiten gespeichert wird das man tot ist und die Person nach dem connecten tot an der selben Stelle aufwacht und eben warten muss. Ist das

**Comment by Kenshiin13** [comment]
Möglichkeit 2 umgesetzt.
https://github.com/Asgard-RP/Dev-Server/commit/fe8340dc7a120ebb50efcd1a027bc047f5790cc5
