### ISSUE TITLE
wenn man escape drückt und im menü soll man keine Menüs öffen können sprich f6 etc.

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#519]

**Comment by Keykubad42** [comment]
Sobald man escape drückt taucht ja das menü auf karte einstellungen etc. wäre gut wenn man dort eine tastensperre einrichtet, das tasten wie z.B. f3, f6, m nicht mehr funktioniert

**Comment by Kenshiin13** [comment]
Für F3 und M nicht reproduzierbar. F7 (pdextras) wurde dahingehend geupdated. Für den jobscreator (f6) kann ich das nicht machen.

**Comment by Keykubad42** [comment]
ja passt kannst issue closen
