### ISSUE TITLE
Mapping Bug Md gebäude in sandy shore man fällt durch map

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#523]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/197656653-8467b9e7-96d9-45d2-897c-303e7e91cd5d.png)

**Comment by Kenshiin13** [comment]
Benutzen wir dort ein MLO oder ist das vanilla?

**Comment by Keykubad42** [comment]
@Kenshiin13  Vanilla

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/198881545-936ab821-1f45-4a31-874c-51b104352e57.png)

**Comment by Tyson1991** [comment]
![Image](https://user-images.githubusercontent.com/109436524/199699130-65e7e084-ed4f-443a-bfaa-968b048f07ff.png)

**Comment by Tyson1991** [comment]
@Kenshiin13 du müsstes einmal in den Vanilla files prüfen was da schief gelaufen ist, vermutlich nach dem Update wo das Problem mit dem Hangar bestand ist das hier vermutlich passiert, ich habe ein MLO auf dem DEv Server eingefügt und dann gesehen das es das Standard gebäude ist das Fehlt

**Comment by Tyson1991** [comment]
Gelöst .
