### ISSUE TITLE
Luft (unter wasser atmen) Leiste dafür erstellen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#524]

**Comment by Keykubad42** [comment]
Da die Lebensanzeige etc raus genommen wurde wäre es cool irgendwie zu sehen, wie viel luft man unter wasser noch zum atmen hat. Vielleicht mit wasserblasen neben der minimap oder sowas. Muss dann von einem von euch gemacht werden und von tobi designt :)

**Comment by Kenshiin13** [comment]
Ich kümmere mich drum

**Comment by Keykubad42** [comment]
@Kenshiin13. Ist ja eine Funktion die ebreits in GTA gegeben ist, in der standard map quasi. Also wenn man die nutzen kann dann easy.   Du die Funktion Tobi das Design?

**Comment by Kenshiin13** [comment]
habe ich mal an tobi weitergeleitet für das design.

**Comment by Keykubad42** [comment]
Keine Nötigkeit mehr
