### ISSUE TITLE
Wenn man die Range des ingamevoice verändert soll es visuell sein.  So ein Marker am besten von dem Radius

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#527]

**Comment by Keykubad42** [comment]
Marker (1) in schwarz transparenz 100-150 (a)

Der Marker soll in der Breite sein. des Radius sein

Das heißt bei Flüstern realtiv klein bei normal dann größer etc.

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/2982a4e5622d5cb70470a491919b70768394175a
