### ISSUE TITLE
Glitchroll muss entfernt werden

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#532]

**Comment by Keykubad42** [comment]
Am besten @AGNayzon fragenw as das ist

**Comment by AGNayzon** [comment]
https://www.youtube.com/watch?v=l8mWkxuZICs
Sekunde 17

**Comment by Kenshiin13** [comment]
wie soll ich das fixen xD gibts da überhaupt einen fix für?

**Comment by Kenshiin13** [comment]
![image](https://user-images.githubusercontent.com/63159154/199535285-dfb166e6-fed1-476c-b8d4-0b1373c7276f.png)
