### ISSUE TITLE
Copnet PD kann nicht mehr drauf zugreifen..

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#533]

**Comment by Keykubad42** [comment]
Die Probs die vorher das copnet ausgelöst haben tun es nicht mehr

**Comment by Keykubad42** [comment]
Das ist sehr wichtig!!!!!

**Comment by Keykubad42** [comment]
am besten auch direkt updaten

**Comment by mjiruobe** [comment]
Update hab ich gelassen, da man das nicht mit den Hashes verbinden kann weil es verschlüsselt ist. Ansonsten gefixt
