### ISSUE TITLE
Rucksäcke sind nicht sichtbar?

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#535]

**Comment by Keykubad42** [comment]
https://medal.tv/games/gta-v/clips/GBrR6NitPpuDf/d1337A8oIihX?invite=cr-MSx4SHIsNjI1MDQ2MDIs

**Comment by Keykubad42** [comment]
vielleicht liegt es an qs backpack?

**Comment by Kenshiin13** [comment]
liegt definitiv an qs-backpack.
