### ISSUE TITLE
Pool Size bug beheben

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#537]

**Comment by Keykubad42** [comment]
trotz @Kenshiin13´s Beschriebung wie man das fixxen kann kommt es noch extrem oft auf. Muss am Server liegen!

**Comment by Kenshiin13** [comment]
Das ist 100% ein client issue. bei mir passiert das ja auch nicht und ich fliege ganze zeit mit noclip. Extended Texture Budget in den GTA Einstellungen niedrieger machen, wenn die GPU zu wenig VRAM hat.
