### ISSUE TITLE
[BUG] Mapping Fehler *Salieri*

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#548]
PLZ 150

Unsichtbare Wand
![image](https://user-images.githubusercontent.com/114504764/200164374-dfba3711-555f-409e-9ccf-22db4ed18a5c.png)

Boden Fehler
![image](https://user-images.githubusercontent.com/114504764/200164401-8efeb842-3379-4f91-a23d-b77ab7589d0d.png)
![image](https://user-images.githubusercontent.com/114504764/200164409-52b435ff-a8d7-4087-a065-c180084d2eca.png)

Drauen sieht man nichts
![image](https://user-images.githubusercontent.com/114504764/200164429-9ad4b022-40eb-476a-a4aa-221b910fe038.png)

Mapping Fehler
![image](https://user-images.githubusercontent.com/114504764/200164447-2838fba6-e051-4deb-a1be-cadd41c06b8d.png)
![image](https://user-images.githubusercontent.com/114504764/200164452-71eb77b2-6191-4e50-aab5-b16b7e1e3650.png)

**Comment by Keykubad42** [comment]
/home/asgard-main/server-data/resources/[MLO]/[illegal_shop] brofx mafia
