### ISSUE TITLE
Frakgaragensystem erstellen (esx policejob garagensystem umschrieben ode rkopieren)

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#552]

**Comment by Keykubad42** [comment]
Das garagen system des esx police job bitte umschrieben oder kopieren das es als garagenscript funktioniert für fraks natürlich. Das heißt sowolh ausparken kaufen und auch speichern tuning etc beim einparken

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/64b0a7529acc57e50452b538f6630c6c4a09d4bf
