### ISSUE TITLE
Commands entfernen/hinzufüghen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#555]

**Comment by Keykubad42** [comment]
/prog

/alarm on & off  


zustzälich
/testnotify
/testdialog
/washtest
entfernen diese sachen

https://medal.tv/games/gta-v/clips/HIgeyImeqlzYh/d1337IiMJLTp?invite=cr-MSxscXQsNjI1MDQ2MDIs

**Comment by Keykubad42** [comment]
/testnotify
/testdialog
wurde entfernt rest muss noch

**Comment by Kenshiin13** [comment]
prog entfernt, rest nicht gefunden
