### ISSUE TITLE
Blinker auf die Pfeiltasten platzieren

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#573]

**Comment by Keykubad42** [comment]
Es ist gerade so:

"?" = linker Blinker
"`"= rechter Blinker
"idk" = Warnblinker
"idk" = alle Blinker ausstellen

Und soll so:

Linke Pfeiltaste = linker Blinker
rechte Pfeiltaste = rechter Blinker
Pfeiltaste oben = Warnblinker
Pfeiltaste unten = alle Blinker ausstellen

**Comment by Kenshiin13** [comment]
https://github.com/Asgard-RP/Dev-Server/commit/6e549c891883fad7bc8fbc8995006289e69813ff
