### ISSUE TITLE
Recherche: Kennzeichen abmachen script

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#576]

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/204031397-4b8acdb0-be83-445e-973b-8bcfb8728fea.png)

**Comment by Keykubad42** [comment]
Man soll die Kennzeichen abmachen und auf andere Autos packen

**Comment by Keykubad42** [comment]
![Image](https://user-images.githubusercontent.com/109434078/204031488-c96f2478-ccc5-46fa-923a-efb512a6c86b.png)

**Comment by Keykubad42** [comment]
Bitte nach so etwas suchen und finden

**Comment by Keykubad42** [comment]
Alle Recherchen kannst du gerne auf das Team verteilen

**Comment by AGNayzon** [comment]
https://www.youtube.com/watch?v=TSfBxOWeoqA
Was besseres finde ich nicht.
$00.00
