### ISSUE TITLE
Katzen in catcafe als npcs einführen mit polyzone etc.

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#577]

**Comment by Keykubad42** [comment]
Katzen sollen im catcafe rumlaufen und per polyzone auf das catcafe beschränkt werden.

**Comment by Keykubad42** [comment]
es soll in der config möglich sein mehrere zonen mit anderen npcs zu erstellen

Das heißt ich kann auch iene polyzone im wald erstellen und sagen in der polyzone sollen 10 rehe rumlaufen

**Comment by 69Gkay** [comment]
Done
