### ISSUE TITLE
Tuning-Werkstatt für Helikopter und Flugzeuge

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#585]

**Comment by Keykubad42** [comment]
Helis und FLugzeuge sollen die Möglichkeit haben die Farben zu ändern. Nur die Farben reicht komplett aus. Das heißt man müsste das lscustoms script eventuell aufgreifen und abändern

**Comment by Keykubad42** [comment]
Kannst dafür auch gerne einfach das esx lscustoms verwnenden das ist dir überlassen. Man muss nur farbe wehcseln können. Ode rdu nimmst kibra und blendest alles andere aus weiß nicht

**Comment by Kenshiin13** [comment]
![image](https://user-images.githubusercontent.com/63159154/221362036-c18619c7-16c7-4c0f-bec2-b60ee9c91fbf.png)
passt so?

**Comment by Kenshiin13** [comment]
![image](https://user-images.githubusercontent.com/63159154/221362055-294493bc-dcf9-41a2-a16b-e9d89e55253b.png)


passt so?
