### ISSUE TITLE
Garagenscript Autos gehen beim ausparken kaputt

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#6]
Habe Fast alle Garagen heute am 13.09.22 ausprobiert und bei mir war das Fahrzeug immer Ganz. 
Komisch irgendwie. 

Gruss Tyson

**Comment by mjiruobe** [comment]
Ich habe Motel Parking ein Auto ausgeparkt und es war nicht kaputt. Danach habe ich es etwas kaputt gemacht und es wurde genauso gespawnt, wie eingeparkt. Allerdings ist mir aufgefallen, dass bei qs garages Config.Deformation = true ist
