### ISSUE TITLE
Tuner:

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#605]
_**2 verschiedene Tuner...**_
1. Ein Tuner der für **jeden** Zugänglich sein soll. Die Preise von allem erhöhen.
-> Alles was den Motor betrifft um 2x.
-> Alles was das Aussehen betrifft um 5x.
2. Ein Tuner den man nur mit **einem JOB** machen kann.

Das heißt man muss das Standard script kopieren und auf Jobs festlegen. Damit wir beides haben einen normalen und einen das wir auf jobs festlegen können. 

Das job bezogene Mechanikerscript  ist doppelt so teuer und funktioniert nur wenn der mechaniker geöffnet ist also über gk-blips
-> NOS soll kaufbar sein. [https://github.com/Asgard-RP/Backlog/issues/615]
-> Farbige Scheinwerfer  ls customs Lichterfarben abändern von scheinwerfern (Ist eine gta funktion) Gta Online arenawar
-> Anti-Lag soll über 400 Asgard Coins kaufbar sein. [Soll auf das Kennzeichen getriggert werden]

**Comment by AGNayzon** [comment]
@Keykubad42

**Comment by Keykubad42** [comment]
Vorraussetzung: https://github.com/Asgard-RP/Backlog/issues/454
