### ISSUE TITLE
Durchsuchen und Abnehmen:

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#607]
**WENNS GEHT:**
Man soll Tote durchsuchen, aber nicht abnehmen können.

**Wenns nicht geht:**
Man soll Tote nicht mehr durchsuchen, schweige denn irgendwas abnehmen können.

**Comment by AGNayzon** [comment]
@Keykubad42

**Comment by 69Gkay** [comment]
Done
