### ISSUE TITLE
Kampfunfähigkeit:

### ISSUE THREAD

**Issue by AGNayzon** [Asgard-RP/Backlog#608]
Wenn man von einem Medic hochgeholt wurde, soll man 5 Kampfunfähig sein.
Wenn man ausblutet, so wird man für 15 Minuten Kampfunfähig sein.

Kampfunfähig: Man kann für eine Gewisse Zeit, keine Waffe ziehen oder Drive-Byn.

**Comment by AGNayzon** [comment]
@Keykubad42

**Comment by Keykubad42** [comment]
Entweder du musst da etwas finden oder es selbst schreiben

**Comment by Keykubad42** [comment]
gka ykam nicht weite rkenshin übernimmt
