### ISSUE TITLE
Recherche: Spitzhacken Bug. Bei den illegalen Routen. GK-farmer Modus 2

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#612]

**Comment by Keykubad42** [comment]
Bei manchen tritt es direkt auf bei manchen später, bei manchen gar nicht

== sporadischer Bug

Wie kann man es reproduzieren: Eine Person farmt, bei der Eisen oder der Stahlroute. (GK-farmer Modus2) Der Prob bleibt dann in der Hand ob es auf der Handwaffenroute auch der Fall ist müsste man testen. Bei mir tritt dieser Fehler auf gar keiner Route auf. Sobald man den Prob in der Hand hat kann man veruschen rezuconnecten. Bei manchen klappt es bei manchen ist der Prob aber immer noch da.




![Image](https://user-images.githubusercontent.com/109434078/215366736-9f680614-13ae-4a2d-a98c-19e4745e5114.png)

**Comment by Keykubad42** [comment]
F8 konsole spuckt das hier aus:

![Image](https://user-images.githubusercontent.com/109434078/215671435-5f0d2e14-e940-45ea-ad82-0a3439a24ac5.png)


https://medal.tv/games/gta-v/clips/T2RtYNPrNtgEK/d1337uOdfzLB?invite=cr-MSxTQkwsNjc2NzE5NzUs

Und wenn jemand mit diesem Bug veruscht in ein Auto einzusteigne funktioniert es entweder nicht richtig oder das auto fliegt um die Lüfte. 



![Image](https://user-images.githubusercontent.com/109434078/215671638-e4a60faa-fc6f-49e0-a38e-b8f2d3c551fc.png)

**Comment by Keykubad42** [comment]
und so sieht es aus wenn man disconnectet

**Comment by Keykubad42** [comment]
Man weiß immer noch nicht woran es liegt

**Comment by Keykubad42** [comment]
Bitte nach Emotes oder ANimationen oder Scenarios eventuell im neuen dp emotes menü suchen was man fürs farmen nutzen könnte statt den spitzhacken-emote

**Comment by Keykubad42** [comment]
Alle Recherchen kannst du gerne auf das Team verteilen

**Comment by AGNayzon** [comment]
Neue Möglichkeiten:
Hammern oder Schweißen.
