### ISSUE TITLE
Frauen Makeup etc. Vexcreator

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#618]

**Comment by Keykubad42** [comment]
Hey die schminke kann irgendwie keine Farben abspeichern bsp Rush wird grün oder meine normale schminke wird Pink und Augenbrauen kann man auch nicht ändern



![Image](https://user-images.githubusercontent.com/109434078/215371945-cac4ad6e-5c89-4355-a6a3-38f92a8a545b.png)

**Comment by Kenshiin13** [comment]
Sollte gefixed sein bitte testen und dann selbstständig closen

**Comment by Keykubad42** [comment]
Ist nicht gefixxed. Man kann diese Sachen beim Friseur alles nicht ändern. Nur über skincreator

**Comment by Kenshiin13** [comment]
geht jetzt
