### ISSUE TITLE
Npc spawner fixxen das die sich direkt bewegen

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#635]

**Comment by Keykubad42** [comment]
Wieso die peds sich nicht bewegen von alleine musst du herauskriegen. Laut deiner Aussage weiß Kenshin es ja auch nicht. Ich habe dir eben das hunting scirpt geschickt da klappt es ja also kannst du es dir einfach copyn.

**Comment by 69Gkay** [comment]
Gelöst, (du kannst dich jetzt bewegen)
