### ISSUE TITLE
Qs Inventory - Job-Creator Kompatibilitätsprobleme

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#83]
Lager und Waffenlager: Items lassen sich per Qs-Inventory nicht in das jeweilige Lager verschieben. Objekte werden nicht erkannt.

Überprüfen wie Jobcreator und Qs miteinander arbeiten, wenn überhaupt. :/

**Comment by Asrothear** [comment]
\resources\[creators]\jobs_creator\integrations\sh_integrations.lua
INVENTORY_TO_USE aus qs umgestellt
