### ISSUE TITLE
Gefängniskleidung ändern

### ISSUE THREAD

**Issue by Keykubad42** [Asgard-RP/Backlog#9]

**Comment by Asrothear** [comment]
Welche Kleidung ist aktuell gesetzt, wenn überhaupt?
Auf welche Kleidung soll gewechselt werden?

**Comment by Keykubad42** [comment]
Diese Prisonkleidung halt, Ich muss mal schauen habe jetzt aus gemacht. Die Kleidung die gesetztz ist ist bei pdextras drin in kenshins scirpt

**Comment by Keykubad42** [comment]
Pull Request wurde bereits überprüft und geschlossen
